"""add unique constrain for customer sync rejected

Revision ID: 0568446634d5
Revises: 5db2dc911496
Create Date: 2026-07-21 12:19:10.497653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0568446634d5'
down_revision: Union[str, Sequence[str], None] = '5db2dc911496'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_customer_sync_reject_customer_id_sync_date', 'rdl_customer_sync_reject', ['customer_id', 'sync_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_customer_sync_reject_customer_id_sync_date', 'rdl_customer_sync_reject', type_='unique')
    # ### end Alembic commands ###
