"""add transform skip model

Revision ID: 0ac526384655
Revises: 2e367628180c
Create Date: 2026-07-21 15:06:45.827880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac526384655'
down_revision: Union[str, Sequence[str], None] = '2e367628180c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_transform_skip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=True),
    sa.Column('da_code', sa.String(length=10), nullable=True),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('sync_date', sa.String(length=10), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_doc_no', 'sync_date', name='uq_transform_skip_invoice_date')
    )
    op.create_index('ix_transform_skip_resolved', 'rdl_transform_skip', ['resolved'], unique=False)
    op.create_index('ix_transform_skip_sync_date', 'rdl_transform_skip', ['sync_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transform_skip_sync_date', table_name='rdl_transform_skip')
    op.drop_index('ix_transform_skip_resolved', table_name='rdl_transform_skip')
    op.drop_table('rdl_transform_skip')
    # ### end Alembic commands ###
