"""make material optional fields nullable

Revision ID: 281c5874d5ba
Revises: b74635d2b24d
Create Date: 2026-07-15 16:26:05.120679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281c5874d5ba'
down_revision: Union[str, Sequence[str], None] = 'b74635d2b24d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpl_material_list', 'distribution_channel',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('rpl_material_list', 'producer_company',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('rpl_material_list', 'team',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('rpl_material_list', 'pack_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('rpl_material_list', 'brand_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('rpl_material_list', 'brand_description',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpl_material_list', 'brand_description',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rpl_material_list', 'brand_name',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('rpl_material_list', 'pack_size',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('rpl_material_list', 'team',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('rpl_material_list', 'producer_company',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('rpl_material_list', 'distribution_channel',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
