"""add allow multiple device column

Revision ID: 3668bda96db2
Revises: c643adeb3e5a
Create Date: 2026-07-22 10:07:06.706941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3668bda96db2'
down_revision: Union[str, Sequence[str], None] = 'c643adeb3e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rdl_user_credential', sa.Column('allow_multi_device', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rdl_user_credential', 'allow_multi_device')
    # ### end Alembic commands ###
