"""add depot, route, user tables with history; drop route_wise_depot

Revision ID: 4081bcfbb5c6
Revises: 2ef5d89a1d88
Create Date: 2026-07-07 10:16:23.494661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4081bcfbb5c6'
down_revision: Union[str, Sequence[str], None] = '2ef5d89a1d88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_depot_list',
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('depot_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('depot_code')
    )
    op.create_table('rdl_route_depot_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rdl_route_list',
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('route_code')
    )
    op.create_table('rdl_user_depot_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rdl_user_list',
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('da_name', sa.String(length=100), nullable=False),
    sa.Column('mobile_no', sa.String(length=15), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('da_code')
    )
    op.create_index(op.f('ix_rdl_user_list_depot_code'), 'rdl_user_list', ['depot_code'], unique=False)
    op.drop_table('rdl_route_wise_depot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_route_wise_depot',
    sa.Column('route_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('route_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('depot_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('depot_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('route_code', name=op.f('rdl_route_wise_depot_pkey'))
    )
    op.drop_index(op.f('ix_rdl_user_list_depot_code'), table_name='rdl_user_list')
    op.drop_table('rdl_user_list')
    op.drop_table('rdl_user_depot_history')
    op.drop_table('rdl_route_list')
    op.drop_table('rdl_route_depot_history')
    op.drop_table('rdl_depot_list')
    # ### end Alembic commands ###
