"""update delivery info sap

Revision ID: 5ced3759d874
Revises: eca85e95f8fc
Create Date: 2026-07-21 09:55:38.218531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ced3759d874'
down_revision: Union[str, Sequence[str], None] = 'eca85e95f8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rdl_delivery_info_sap', sa.Column('route', sa.String(length=6), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rdl_delivery_info_sap', 'route')
    # ### end Alembic commands ###
