"""add sync_log and customer_sync_reject tables

Revision ID: 5db2dc911496
Revises: 5ced3759d874
Create Date: 2026-07-21 11:27:42.178356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5db2dc911496'
down_revision: Union[str, Sequence[str], None] = '5ced3759d874'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_customer_sync_reject',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=True),
    sa.Column('shop_name', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('sync_date', sa.String(length=10), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_reject_resolved', 'rdl_customer_sync_reject', ['resolved'], unique=False)
    op.create_index(op.f('ix_rdl_customer_sync_reject_sync_date'), 'rdl_customer_sync_reject', ['sync_date'], unique=False)
    op.create_table('rdl_sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('sync_date', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rdl_sync_log_sync_date'), 'rdl_sync_log', ['sync_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rdl_sync_log_sync_date'), table_name='rdl_sync_log')
    op.drop_table('rdl_sync_log')
    op.drop_index(op.f('ix_rdl_customer_sync_reject_sync_date'), table_name='rdl_customer_sync_reject')
    op.drop_index('ix_customer_reject_resolved', table_name='rdl_customer_sync_reject')
    op.drop_table('rdl_customer_sync_reject')
    # ### end Alembic commands ###
