"""add all domain models with relationships

Revision ID: 69c3513345fd
Revises: 4081bcfbb5c6
Create Date: 2026-07-15 12:02:11.464072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c3513345fd'
down_revision: Union[str, Sequence[str], None] = '4081bcfbb5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_delivery_info_sap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('delv_no', sa.String(length=10), nullable=False),
    sa.Column('vehicle_no', sa.String(length=25), nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('da_name', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_doc_no')
    )
    op.create_index(op.f('ix_rdl_delivery_info_sap_billing_date'), 'rdl_delivery_info_sap', ['billing_date'], unique=False)
    op.create_table('rpl_customer_sales_org',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('company_code', sa.String(length=10), nullable=False),
    sa.Column('sales_org', sa.String(length=10), nullable=False),
    sa.Column('del_plant', sa.String(length=10), nullable=False),
    sa.Column('pre_cust_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'sales_org', 'del_plant')
    )
    op.create_table('rpl_customer_territory',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('work_area', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', 'team', 'work_area', 'start_date')
    )
    op.create_table('rpl_material_list',
    sa.Column('material_id', sa.String(length=10), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('plant_code', sa.String(length=10), nullable=False),
    sa.Column('sales_org', sa.String(length=10), nullable=False),
    sa.Column('distribution_channel', sa.String(length=10), nullable=False),
    sa.Column('producer_company', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=10), nullable=False),
    sa.Column('pack_size', sa.String(length=20), nullable=False),
    sa.Column('unit_tp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('brand_name', sa.String(length=10), nullable=False),
    sa.Column('brand_description', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('rpl_sales_info_sap',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_pass_no', sa.String(length=10), nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('material_id', sa.String(length=10), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_val', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_type', sa.String(length=4), nullable=False),
    sa.Column('plant', sa.String(length=4), nullable=False),
    sa.Column('sales_org', sa.String(length=4), nullable=False),
    sa.Column('sales_type', sa.String(length=2), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('company_code', sa.String(length=4), nullable=False),
    sa.Column('assignment', sa.String(length=10), nullable=False),
    sa.Column('territory_code', sa.String(length=5), nullable=False),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=5), nullable=True),
    sa.Column('item_category', sa.String(length=4), nullable=False),
    sa.Column('cancel', sa.String(length=1), nullable=True),
    sa.Column('mio_name', sa.String(length=50), nullable=True),
    sa.Column('mio_mobile_no', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_doc_no', 'billing_date', 'material_id', 'batch', name='uq_sales_info_billing_doc_date_material_batch')
    )
    op.create_table('rpl_user_list',
    sa.Column('work_area_t', sa.String(length=10), nullable=False),
    sa.Column('rm_code', sa.String(length=10), nullable=True),
    sa.Column('zm_code', sa.String(length=10), nullable=True),
    sa.Column('sm_code', sa.String(length=10), nullable=True),
    sa.Column('gm_code', sa.String(length=10), nullable=True),
    sa.Column('rm_address', sa.String(length=255), nullable=True),
    sa.Column('zm_address', sa.String(length=255), nullable=True),
    sa.Column('sm_address', sa.String(length=255), nullable=True),
    sa.Column('gm_address', sa.String(length=255), nullable=True),
    sa.Column('sap_user_code', sa.String(length=10), nullable=False),
    sa.Column('sap_next_user_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=55), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('mobile_no', sa.String(length=15), nullable=False),
    sa.Column('designation_id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=55), nullable=False),
    sa.Column('group_name', sa.String(length=55), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('work_area_t')
    )
    op.create_table('rdl_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('working_date', sa.Date(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('late_time_sec', sa.Integer(), nullable=True),
    sa.Column('over_time_sec', sa.Integer(), nullable=True),
    sa.Column('start_image_url', sa.String(length=255), nullable=True),
    sa.Column('end_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('da_code', 'working_date', name='uq_attendance_da_date')
    )
    op.create_index(op.f('ix_rdl_attendance_da_code'), 'rdl_attendance', ['da_code'], unique=False)
    op.create_table('rdl_conveyance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('working_date', sa.Date(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('end_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('travel_duration_sec', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vehicle', sa.String(length=100), nullable=True),
    sa.Column('start_image_url', sa.String(length=255), nullable=True),
    sa.Column('end_image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conveyance_da_date', 'rdl_conveyance', ['da_code', 'working_date'], unique=False)
    op.create_table('rdl_user_credential',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('must_reset', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rdl_user_credential_da_code'), 'rdl_user_credential', ['da_code'], unique=False)
    op.create_table('rpl_customer_list',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('shop_name', sa.String(length=100), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('mobile_no', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('post_code', sa.String(length=10), nullable=False),
    sa.Column('upazila', sa.String(length=50), nullable=False),
    sa.Column('district', sa.String(length=50), nullable=False),
    sa.Column('drug_reg_no', sa.String(length=50), nullable=True),
    sa.Column('customer_group', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_code'], ['rdl_route_list.route_code'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_index(op.f('ix_rpl_customer_list_route_code'), 'rpl_customer_list', ['route_code'], unique=False)
    op.create_table('rdl_customer_location',
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('rdl_customer_visit',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('working_date', sa.Date(), nullable=False),
    sa.Column('visit_type', sa.String(length=10), nullable=False),
    sa.Column('visit_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visit_customer_date', 'rdl_customer_visit', ['customer_id', 'working_date'], unique=False)
    op.create_index('ix_visit_da_date', 'rdl_customer_visit', ['da_code', 'working_date'], unique=False)
    op.create_table('rdl_delivery_collection',
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('gate_pass_no', sa.String(length=10), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('billing_type', sa.String(length=4), nullable=False),
    sa.Column('plant', sa.String(length=4), nullable=False),
    sa.Column('sales_type', sa.String(length=2), nullable=False),
    sa.Column('sales_org', sa.String(length=4), nullable=False),
    sa.Column('delv_no', sa.String(length=10), nullable=False),
    sa.Column('vehicle_no', sa.String(length=25), nullable=False),
    sa.Column('billing_method', sa.String(length=10), nullable=True),
    sa.Column('company_code', sa.String(length=10), nullable=False),
    sa.Column('assignment', sa.String(length=10), nullable=False),
    sa.Column('reference', sa.String(length=10), nullable=False),
    sa.Column('item_category', sa.String(length=10), nullable=False),
    sa.Column('delivery_status', sa.Boolean(), nullable=False),
    sa.Column('delivery_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cash_collection_status', sa.Boolean(), nullable=False),
    sa.Column('cash_collection_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('delivery_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cash_collection_latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cash_collection_longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('invoice_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cash_collection_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('round_down', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('return_status', sa.Boolean(), nullable=False),
    sa.Column('return_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('due_status', sa.Boolean(), nullable=False),
    sa.Column('due_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('return_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('billing_doc_no')
    )
    op.create_index('ix_delivery_customer_date', 'rdl_delivery_collection', ['customer_id', 'billing_date'], unique=False)
    op.create_index('ix_delivery_da_date', 'rdl_delivery_collection', ['da_code', 'billing_date'], unique=False)
    op.create_table('rpl_customer_route_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_code'], ['rdl_route_list.route_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rdl_delivery_return_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('material_id', sa.String(length=10), nullable=False),
    sa.Column('batch', sa.String(length=10), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tp', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('vat', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_val', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('delivery_quantity', sa.Integer(), nullable=False),
    sa.Column('return_quantity', sa.Integer(), nullable=False),
    sa.Column('delivery_net_val', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('return_net_val', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_doc_no'], ['rdl_delivery_collection.billing_doc_no'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['material_id'], ['rpl_material_list.material_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_doc_no', 'material_id', 'batch', name='uq_delivery_collection_billing_doc_material_batch')
    )
    op.create_index(op.f('ix_rdl_delivery_return_item_billing_doc_no'), 'rdl_delivery_return_item', ['billing_doc_no'], unique=False)
    op.create_table('rdl_overdue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('due_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_doc_no'], ['rdl_delivery_collection.billing_doc_no'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_overdue_customer_date', 'rdl_overdue', ['customer_id', 'billing_date'], unique=False)
    op.create_table('rdl_payment_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('billing_doc_no', sa.String(length=10), nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('customer_id', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('payment_type', sa.String(length=10), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['billing_doc_no'], ['rdl_delivery_collection.billing_doc_no'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['rpl_customer_list.customer_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_customer_date', 'rdl_payment_history', ['customer_id', 'payment_date'], unique=False)
    op.create_index('ix_payment_da_date', 'rdl_payment_history', ['da_code', 'payment_date'], unique=False)
    op.create_foreign_key(None, 'rdl_route_depot_history', 'rdl_route_list', ['route_code'], ['route_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rdl_route_depot_history', 'rdl_depot_list', ['depot_code'], ['depot_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rdl_route_list', 'rdl_depot_list', ['depot_code'], ['depot_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rdl_user_depot_history', 'rdl_depot_list', ['depot_code'], ['depot_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rdl_user_depot_history', 'rdl_user_list', ['da_code'], ['da_code'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'rdl_user_list', 'rdl_depot_list', ['depot_code'], ['depot_code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rdl_user_list', type_='foreignkey')
    op.drop_constraint(None, 'rdl_user_depot_history', type_='foreignkey')
    op.drop_constraint(None, 'rdl_user_depot_history', type_='foreignkey')
    op.drop_constraint(None, 'rdl_route_list', type_='foreignkey')
    op.drop_constraint(None, 'rdl_route_depot_history', type_='foreignkey')
    op.drop_constraint(None, 'rdl_route_depot_history', type_='foreignkey')
    op.drop_index('ix_payment_da_date', table_name='rdl_payment_history')
    op.drop_index('ix_payment_customer_date', table_name='rdl_payment_history')
    op.drop_table('rdl_payment_history')
    op.drop_index('ix_overdue_customer_date', table_name='rdl_overdue')
    op.drop_table('rdl_overdue')
    op.drop_index(op.f('ix_rdl_delivery_return_item_billing_doc_no'), table_name='rdl_delivery_return_item')
    op.drop_table('rdl_delivery_return_item')
    op.drop_table('rpl_customer_route_history')
    op.drop_index('ix_delivery_da_date', table_name='rdl_delivery_collection')
    op.drop_index('ix_delivery_customer_date', table_name='rdl_delivery_collection')
    op.drop_table('rdl_delivery_collection')
    op.drop_index('ix_visit_da_date', table_name='rdl_customer_visit')
    op.drop_index('ix_visit_customer_date', table_name='rdl_customer_visit')
    op.drop_table('rdl_customer_visit')
    op.drop_table('rdl_customer_location')
    op.drop_index(op.f('ix_rpl_customer_list_route_code'), table_name='rpl_customer_list')
    op.drop_table('rpl_customer_list')
    op.drop_index(op.f('ix_rdl_user_credential_da_code'), table_name='rdl_user_credential')
    op.drop_table('rdl_user_credential')
    op.drop_index('ix_conveyance_da_date', table_name='rdl_conveyance')
    op.drop_table('rdl_conveyance')
    op.drop_index(op.f('ix_rdl_attendance_da_code'), table_name='rdl_attendance')
    op.drop_table('rdl_attendance')
    op.drop_table('rpl_user_list')
    op.drop_table('rpl_sales_info_sap')
    op.drop_table('rpl_material_list')
    op.drop_table('rpl_customer_territory')
    op.drop_table('rpl_customer_sales_org')
    op.drop_index(op.f('ix_rdl_delivery_info_sap_billing_date'), table_name='rdl_delivery_info_sap')
    op.drop_table('rdl_delivery_info_sap')
    # ### end Alembic commands ###
