"""update string size for user_type

Revision ID: 9d0ce2bae004
Revises: 0568446634d5
Create Date: 2026-07-21 13:00:54.506083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d0ce2bae004'
down_revision: Union[str, Sequence[str], None] = '0568446634d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rdl_user_list', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('rdl_user_list', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rdl_user_list', 'designation',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rdl_user_list', 'user_type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
