"""add refresh_token table

Revision ID: c643adeb3e5a
Revises: 0ac526384655
Create Date: 2026-07-21 17:42:02.213966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c643adeb3e5a'
down_revision: Union[str, Sequence[str], None] = '0ac526384655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('da_code', sa.String(length=10), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['da_code'], ['rdl_user_list.da_code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rdl_refresh_token_token'), 'rdl_refresh_token', ['token'], unique=True)
    op.create_index('ix_refresh_token_da_code', 'rdl_refresh_token', ['da_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refresh_token_da_code', table_name='rdl_refresh_token')
    op.drop_index(op.f('ix_rdl_refresh_token_token'), table_name='rdl_refresh_token')
    op.drop_table('rdl_refresh_token')
    # ### end Alembic commands ###
