"""create route_wise_depot table

Revision ID: cf3223746c33
Revises: 
Create Date: 2026-07-06 10:13:20.746183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3223746c33'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_route_wise_depot',
    sa.Column('route_code', sa.String(length=10), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('depot_code', sa.String(length=10), nullable=False),
    sa.Column('depot_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('route_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rdl_route_wise_depot')
    # ### end Alembic commands ###
