"""add return reason

Revision ID: e329a4aa75c2
Revises: 3668bda96db2
Create Date: 2026-07-22 12:42:18.277794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e329a4aa75c2'
down_revision: Union[str, Sequence[str], None] = '3668bda96db2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rdl_return_reason',
    sa.Column('reason_code', sa.String(length=10), nullable=False),
    sa.Column('reason_name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('reason_code')
    )
    op.add_column('rdl_delivery_return_item', sa.Column('return_reason_code', sa.String(length=10), nullable=True))
    op.create_foreign_key(None, 'rdl_delivery_return_item', 'rdl_return_reason', ['return_reason_code'], ['reason_code'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rdl_delivery_return_item', type_='foreignkey')
    op.drop_column('rdl_delivery_return_item', 'return_reason_code')
    op.drop_table('rdl_return_reason')
    # ### end Alembic commands ###
