"""make customer optional fields nullable

Revision ID: eca85e95f8fc
Revises: 281c5874d5ba
Create Date: 2026-07-15 17:36:45.569285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca85e95f8fc'
down_revision: Union[str, Sequence[str], None] = '281c5874d5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpl_customer_list', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('rpl_customer_list', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('rpl_customer_list', 'street',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('rpl_customer_list', 'post_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('rpl_customer_list', 'upazila',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('rpl_customer_list', 'district',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rpl_customer_list', 'district',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rpl_customer_list', 'upazila',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('rpl_customer_list', 'post_code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('rpl_customer_list', 'street',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('rpl_customer_list', 'mobile_no',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('rpl_customer_list', 'customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
